audits/urls.py
from django.urls import path
from .views import SiteListView, ClientListView, ChecklistWizardView, VendorCreate, VendorUpdate, ChecklistTwoWizardView, ChecklistThreeWizardView
from .forms import *

from . import views

app_name = 'audits'

urlpatterns = [
    path('', views.index, name='index'),
    path('client/', ClientListView.as_view(), name='client'),
    path('client/<int:pk>/', views.clientDetail, name='client-detail'),
    path('allvendor/', views.AllVendorListView.as_view(), name='all-vendor'),
    path('site/', SiteListView.as_view(), name='site'),
    #path('vendor/', views.vendorList, name='vendor'),
    path('vendor/<int:pk>/', views.vendorDetail, name='vendor-detail'),
    path('create-site', views.createSite, name='create-site'),
    path('create-client/', views.createClient, name='create-client'),
    path('create-vendor/', VendorCreate.as_view(), name='create-vendor'),
    path('update-client/<int:pk>/', views.updateClient, name='update-client'),
    path('delete-client/<int:pk>/', views.deleteClient, name='delete-client'),
    path('update-site/<int:pk>/', views.updateSite, name='update-site'),
    path('delete-site/<int:pk>/', views.deleteSite, name='delete-site'),
    path('update-vendor/<int:pk>/', VendorUpdate.as_view(), name='update-vendor'),
    path('delete-vendor/<int:pk>/', views.deleteVendor, name='delete-vendor'),
    path('site-schedule/', views.createSchedule, name='create-schedule'),
    path('checklist-banks/', ChecklistWizardView.as_view(), name='checklist-banks'),
    path('checklist_fuel&gas-stations/', ChecklistTwoWizardView.as_view(), name='checklist-fuel&gas-stations'),
    path('checklist_c&i/', ChecklistThreeWizardView.as_view(), name='checklist-c&i'),
    path('summary/', views.summary, name='summary'),
  
]

audits_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('audits/', include('audits.urls', namespace='audits')),
    path('', include('users.urls')),
]

admin.site.index_title = "Site Audits Management"
admin.site.site_header = "Audits Management Admin"
admin.site.site_title ="Audits"


if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
   
]

audits/views.py
import os
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import ListView, CreateView, UpdateView
from formtools.wizard.views import SessionWizardView
from django.contrib import messages
from django.urls import reverse_lazy
from .models import *
from .forms import *

@login_required
def index(request):
    return render(request, 'audits/index.html')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    context_object_name = 'clients'

 
@login_required
def clientDetail(request, pk):
    client = Client.objects.get(id=pk)
    sites = Site.objects.filter(client=client)
    total_site = Site.objects.filter(client=client).count()
    context = {
        'client': client,
        'sites': sites,
        'total_site': total_site
    }
    return render(request, 'audits/clientDetail.html', context)


class SiteListView(LoginRequiredMixin, ListView):
    model = Site
    template_name = 'audits/site.html'
    context_object_name = 'sites'
    
    ordering = ['-date_added']
    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)
        context['allSites'] = Site.objects.all().count()
        return context



class AllVendorListView(ListView):
    model = Vendor
    template_name = 'audits/all_vendor.html'
    context_object_name = 'vendors'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_staff:
            context['vendors'] = context['vendors'].all()
        else:
            context['vendors'] = context['vendors'].filter(user=self.request.user) 
        
        #context['count'] = context['vendors'].filter(complete=True).count()
        return context
   

# def vendorList(request):
#     vendors = Vendor.objects.filter(user=request.user)
#     context = {
#         'vendors': vendors
#     }
#     return render(request, 'audits/vendor_list.html', context)


@login_required
def createSite(request):
    form = SiteForm()
    if request.method == 'POST':
        print('Printing POST:', request.POST)
        form = SiteForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Site successfully created!")
            return redirect('audits:site')
        messages.error(request, "There was an Error while filling the form, Please re-check!")

    context = {
        'form': form
    }
    return render(request, 'audits/site_form.html', context)


@login_required
def createClient(request):
    form = ClientForm()
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            
            messages.success(request, "One new client successfully added!")
            return redirect('audits:client')
        messages.error(request, "There was an Error filling the form, Please re-check!")

    context = {
        'form': form
    }

    
    return render(request, 'audits/client_form.html', context)

def summary(request):
    sites = Site.objects.all().count()
    smesClients = Client.objects.filter(category="SMEs").count()
    candIClients = Client.objects.filter(category="C&I").count()
    totalClients = Client.objects.all().count()
    schedules = Schedule.objects.all().count()
    audited = Schedule.objects.filter(status='Audited').count()
    pendingAudit = Schedule.objects.filter(status='Pending Audit').count()
    vendors = Vendor.objects.all().count()
    
    # site = Site.objects.filter(status='Pending').count()
    
    context = {
        'sites': sites,
        'smesClients': smesClients,
        'candIClients': candIClients,
        'totalClients': totalClients,
        'schedules': schedules,
        'vendors': vendors,
        'audited': audited,
        'pendingAudit': pendingAudit,
    }
    return render(request, 'audits/summary.html', context)


class VendorCreate(LoginRequiredMixin, CreateView):
    model = Vendor
    fields = ['name', 'representative', 'designation', 'contact', 'email', 'date_created']
    success_url = reverse_lazy('audits:all-vendor')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(VendorCreate, self).form_valid(form)





@login_required
def vendorDetail(request, pk):
    vendor = Vendor.objects.get(id=pk)
    dates = []
    schedules = Schedule.objects.all()
    sites = []
    for schedule in schedules:
        
        if schedule.vendor == vendor:
            sites.append(schedule.site)
            dates.append(schedule.date_assigned)

    print(dates)
        
    print(sites)
    context = {
        'vendor': vendor,
        'sites': sites,
        'dates': dates
    }
    return render(request, 'audits/vendorDetail.html', context)


@login_required
def updateClient(request, pk):
    client = Client.objects.get(id=pk)
    form = ClientForm(instance=client)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect('audits:client')

    context = {
        'form': form
    }
    return render(request, 'audits/update_client.html', context)


@login_required
def deleteClient(request, pk):
    client = Client.objects.get(id=pk)
    if request.method == 'POST':
        client.delete()
        return redirect('audits:client')
    context = {
        'client': client
    }
    return render(request, 'audits/delete_client.html', context)


@login_required
def updateSite(request, pk):
    site = Site.objects.get(id=pk)
    form = SiteForm(instance=site)
    if request.method == 'POST':
        form = SiteForm(request.POST, instance=site)
        if form.is_valid():
            form.save()
            return redirect('audits:site')

    context = {
        'form': form
    }
    return render(request, 'audits/update_site.html', context)


@login_required
def deleteSite(request, pk):
    site = Site.objects.get(id=pk)
    if request.method == 'POST':
        site.delete()
        return redirect('audits:site')
    context = {
        'site': site
    }
    return render(request, 'audits/delete_site.html', context)



class VendorUpdate(UpdateView):
    model = Vendor
    template_name = 'audits/update_vendor.html'
    success_url = reverse_lazy('audits:all-vendor')
    fields = ['name', 'representative', 'designation', 'contact', 'email', 'date_created']


@login_required
def updateVendor(request, pk):
    vendor = Vendor.objects.get(id=pk)
    form = VendorForm(instance=vendor)
    if request.method == 'POST':
        form = VendorForm(request.POST, instance=vendor)
        if form.is_valid():
            form.save()
            return redirect('')

    context = {
        'form': form
    }
    return render(request, 'audits/update_vendor.html', context)


@login_required
def deleteVendor(request, pk):
    vendor = Vendor.objects.get(id=pk)
    if request.method == 'POST':
        vendor.delete()
        return redirect('audits:all-vendor')
    context = {
        'vendor': vendor
    }
    return render(request, 'audits/delete_vendor.html', context)


@login_required
def createSchedule(request):

    form = ScheduleForm()
    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {
        'form': form
    }
    return render(request, 'audits/site_schedule.html', context)


class ChecklistWizardView(SessionWizardView):
    template_name = "audits/temp.html"
    form_list = [
        PageOneForm, PageTwoForm, PageThreeForm, PageFourForm, PageFiveForm
    ]

    file_storage = FileSystemStorage(
        location=os.path.join(settings.MEDIA_ROOT, 'photos'))
    

    def done(self, form_list, form_dict, **kwargs):
        form_data = [form.cleaned_data for form in form_list]
        #print("FORM DATA",form_data)
        checklist = Checklist(
            client=form_data[0]['client'], branch=form_data[0]['branch'], site_address=form_data[0]['site_address'], site_code=form_data[0]['site_code'], latitude=form_data[0]['latitude'],
            longitude=form_data[0]['longitude'], business_type=form_data[0]['business_type'], contact_person_name=form_data[0]['contact_person_name'], vendor=form_data[0]['vendor'],
            auditor_name=form_data[0]['auditor_name'],
            auditor_phone=form_data[0]['auditor_phone'], auditDate=form_data[0]['auditDate'], location=form_data[0]['location'], split_1=form_data[0]['split_1'], split_2=form_data[0]['split_2'],
            split_3=form_data[0]['split_3'], split_4=form_data[0]['split_4'], standing_unit_1=form_data[0]['standing_unit_1'], standing_unit_2=form_data[0]['standing_unit_2'], standing_unit_3=form_data[0]['standing_unit_3'],
            comment=form_data[0]['comment'], florescent=form_data[0]['florescent'], led=form_data[0]['led'], halogen=form_data[0]['halogen'], energy_saver=form_data[0]['energy_saver'],
            panel_light=form_data[0]['panel_light'], other_lights=form_data[0]['other_lights'], desktop=form_data[1]['desktop'], laptop=form_data[1]['laptop'], printer=form_data[1]['printer'],
            counting_machine=form_data[1]['counting_machine'], scanner=form_data[1]['scanner'], atms=form_data[1]['atms'], tv=form_data[1]['tv'], water_dispenser=form_data[1]['water_dispenser'],
            exchange_rate_board=form_data[1]['exchange_rate_board'], signage_light=form_data[1]['signage_light'], water_pump=form_data[1]['water_pump'], fan=form_data[1]['fan'], microwave=form_data[1]['microwave'],

templates/audits/checklist_bank.html
{% extends 'base.html' %} 


{% block title %}
    Checklist
{% endblock title %}
    

{% load widget_tweaks %} 

{% load crispy_forms_tags %} 

{% block content %}
<div class="form-group-lg">
    <form class="form-control" action="" method="POST">
        <div class="form-group">
            {% csrf_token %} {{ form|crispy }}
            <a class="btn btn-outline-info btn-sm" href="">Return Back</a>
            <input type="submit" value="Submit">
        </div>
    </form>
</div>

{% endblock %}

templates/audits/clientDetail.html
{% extends 'base.html' %} 

{% block content %}
<div class="content">
    <div>
        
        <a class="mr-2" href="#"><strong>Created by:</strong> {{ client.user }}</a>
        <small class="text-muted"><strong>Date Created:</strong> {{ client.date_created|date:"F d, Y"}}</small>
    
        <h2><strong>Client:</strong> {{ client.name }}</h2>
        <p class="article-content"><strong>Contact:</strong> {{ client.rep_name }}</p>
        <p class="article-content"><strong>Designation:</strong> {{ client.designation }}</p>
        <p class="article-content"><strong>Phone:</strong> {{ client.phone }}</p>
        <p class="article-content"><strong>Email:</strong> {{ client.email }}</p>
        <p class="article-content"><strong>Number of sites:</strong> {{ total_site }}</p>
    </div>
    
</div>
<div>
    <table class="table table-striped table-hover table-sm">
        <tr>
            <th>Client</th>
            <th>Branch</th>
            <th>Address</th>
            <th>State</th>
            <th>Region</th>
            <th>Contact Person</th>
            <th>Designation</th>
            <th>Email</th>
            <th>Contact Number</th>
            <th>Date Created</th>
        </tr>
      {% for site in sites %}
        <tr>
            <td>{{site.client}}</td>
            <td>{{site.name}}</td>
            <td>{{site.address}}</td>
            <td>{{site.state}}</td>
            <td>{{site.region}}</td>
            <td>{{site.contact}}</td>
            <td>{{site.designation}}</td>
            <td>{{site.email}}</td>
            <td>{{site.phone}}</td>
            <td>{{site.date_added|date}}</td>
        </tr>
        {% endfor %}
    </table>
        
</div>

{% endblock %}

templates/audits/client_form.html
{% extends 'base.html' %} 

{% block content %}
<div class="content-section">

  {% if messages %}
      {% for message in messages %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
      {% endfor %}
  {% endif %}
    
  <form action="" method="POST">
    {% csrf_token %}
    <fieldset class="form-group" class="uniForm">
      <legend class="border-bottom mb-4">New Client</legend>
      {{ form.as_p }}
    </fieldset>
    <div class="form-group">
      <a class="btn btn-outline-info btn-sm" href="{% url 'audits:client' %}">Return Back</a>
      <button class="btn btn-outline-info btn-sm" type="submit">Create</button>
    </div>
  </form>
</div>

{% endblock %}

templates/audits/client_list.html
{% extends 'base.html' %} 

{% block title %}
    Clients
{% endblock title %}
    

{% block content %}

{% if messages %}
    {% for message in messages %}
     <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
    
<a class="btn btn-secondary btn-sm" href="{% url 'audits:create-client' %}">Create Client</a> 
<div class="content">
    
    {% for client in clients %}

    <div class="card card-body">

        
        <a class="mr-2" href="#"><strong>User:</strong> {{ client.user }}</a>
        <small class="text-muted"><strong>Date Created:</strong> {{ client.date_created|date:"F d, Y"}}</small>
        
        <h2><a class="article-title" href="{% url 'audits:client-detail' client.id %}"><strong>Client:</strong> {{ client.name }}</a></h2>
        <p class="article-content"><strong>Contact:</strong> {{ client.rep_name }}</p>
        <p class="article-content"><strong>Designation:</strong> {{ client.designation }}</p>
        <p class="article-content"><strong>Phone:</strong> {{ client.phone }}</p>
        <p class="article-content"><strong>Email:</strong> {{ client.email }}</p>
        <div>
            <a class="btn btn-primary btn-sm" href="{% url 'audits:update-client' client.id %}">Update Client</a>
            <a class="btn btn-danger btn-sm" href="{% url 'audits:delete-client' client.id %}">Delete Client</a>
        </div>

    </div>

    {% endfor %}
</div>

{% endblock %}

templates/audits/done.html
{% extends 'base.html' %} 

{% block content %}
<p>You have successfully submited your report</p>
{% endblock %}

templates/audits/site.html
{% extends "base.html" %} 


{% block title %}
    Sites List
{% endblock title %}
    


{% block content %}


<hr>

{% if messages %}
      {% for message in messages %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
    {% csrf_token %} 
<div class="card card-body">
    <div>
        <a class="btn btn-secondary btn-sm" href="{% url 'audits:create-site' %}">Create Site</a>
        <a class="btn btn-secondary btn-sm" href="{% url 'audits:create-schedule' %}">Create Schedule</a>
    </div>
    <table class="table table-striped table-hover table-sm">
        <tr>
            <th>Clients</th>
            <th>Branch</th>
            <th>Address</th>
            <th>State</th>
            <th>Region</th>
            <th>Contact Person</th>
            <th>Designation</th>
            <th>Email</th>
            <th>Contact Number</th>
            <th>Date Created</th>
            <th></th>
            <th></th>
        </tr>
        {% for site in sites %}
        <tr>
            <td>{{site.client}}</td>
            <td>{{site.name}}</td>
            <td>{{site.address}}</td>
            <td>{{site.state}}</td>
            <td>{{site.region}}</td>
            <td>{{site.contact}}</td>
            <td>{{site.designation}}</td>
            <td>{{site.email}}</td>
            <td>{{site.phone}}</td>
            <td>{{site.date_added|date}}</td>
            <td><a class="btn btn-primary btn-sm" href="{% url 'audits:update-site' site.id %}">Update</a></>
            <td><a class="btn btn-danger btn-sm" href="{% url 'audits:delete-site' site.id %}">Delete</a></td>

        </tr>
        {% endfor %}
    </table>
</div>







{% endblock %}

templates/audits/site_schedule.html
{% extends 'base.html' %} 


{% block title %}
  Schedule
{% endblock title %}
  

{% block content %}
<div class="content-section">
  <form action="" method="POST">
    {% csrf_token %}
    <fieldset class="form-group" class="uniForm">
      <legend class="border-bottom mb-4">New Schedule</legend>
      {{ form.as_p }}
    </fieldset>
    <div class="form-group">
      <a class="btn btn-outline-info btn-sm" href="{% url 'audits:site' %}">Return Back</a>
      <button class="btn btn-outline-info btn-sm" type="submit">Create</button>
    </div>
  </form>
</div>

{% endblock %}

templates/audits/summary.html
{% extends 'base.html' %} 
{% block title %}
    Summary
{% endblock title %}



{% block content %}
        
<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title text-black">Total Sites</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ sites }}</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title text-black">Audited Sites</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ audited }}</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title text-black">Pending Audit</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ pendingAudit }}</h3>
                </div>
            </div>
        </div>
    </div> 
</div>

<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title text-black">SMEs Clients</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ smesClients }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title text-black">C&I Clients</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ candIClients }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title">Total Clients</h5>
                </div>
                <div class="card-body text-black">
                    <h3 class="card-title">{{ totalClients }}</h3>
                </div>
            </div>
        </div>
    </div>
    
    
</div>

<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title text-black">Vendors</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ vendors }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-black mb-3" id="total-sites">
                <div class="card-header ">
                    <h5 class="card-title text-black">Total Schedules</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ schedules }}</h3>
                </div>
            </div>
        </div>
    </div>
    
    
</div>


{% endblock %}

templates/audits/temp.html
{% extends "base.html" %} 


{% block title %}
    Checklist for Bank
{% endblock title %}
    

{% load i18n %} 

{% load bootstrap4 %} 

{% bootstrap_messages %} 

{% block content %}
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<div class="col-md-6 col-lg">
    <div class="msg">
        {% if wizard.steps.index == 0 %}
            <h3>Customer's Information | Cooling Information | Lighting Details</h3>
            <h5>Kindly fill as appropriate.</h5>
        {% elif wizard.steps.index == 1 %}
            <h3>Electrical Appliances</h3>
            <h5>Enter the counts of each of the appliances as listed below.</h5>
        {% elif wizard.steps.index == 2 %}
            <h3>Existing Power | Critical Loads | Backup Information</h3>
            <h5>All values should be in kVA or kW.</h5>
        {% elif wizard.steps.index == 3 %}
            <h3>Building Information</h3>
        
        {% elif wizard.steps.index == 4 %}
            <h3> Equipment Room | Safety and Client's Sign Off </h3>
                   
        {% endif %}
       
    </div>
</div>

<div class="col-md-6">
    <form class="submission-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ wizard.management_form }} 
            
            {% if wizard.form.forms %} 
                {{ wizard.form.management_form }} 
                {% for form in wizard.form.forms %} 
                    {% bootstrap_form form %} 
                {% endfor %} 
            {% else %}
                <p><strong>{% bootstrap_form wizard.form %}</strong></p> 
            
            {% endif %}
        </table>
        {% if wizard.steps.prev %}
            <button class="btn btn-primary" name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">
            {% trans "first step" %}
            </button>
            <button class="btn btn-primary" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">
            {% trans "previous step" %}
            </button> 
        {% endif %}
        {% if wizard.steps.index < 4 %}
            <input class="btn btn-primary" type="submit" value="{% trans 'next' %}" />
        {% elif wizard.steps.index == 4 %}
            <input class="btn btn-primary" type="submit" value="{% trans 'submit' %}" />
        {% endif %}
    </form>
</div>
{% endblock %}

templates/audits/temp_2.html
{% extends "base.html" %} 


{% block title %}
    Checklist for Fuel & Gas Stations
{% endblock title %}
    

{% load i18n %} 

{% load bootstrap4 %} 

{% bootstrap_messages %} 

{% block content %}
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<div class="col-md-6 col-lg">
    <div class="msg">
        {% if wizard.steps.index == 0 %}
        <h3>Customer's Information | Pumps and Cooling Details</h3>
        <h5>Kindly fill as appropriate.</h5>
        {% elif wizard.steps.index == 1 %}
        <h3>Lightings and Electrical Appliances </h3>

        {% elif wizard.steps.index == 2 %}
        <h3>Building | Operation Hour | Safety and Sign Off</h3>

       
        {% endif %} 
       
    </div>
</div>

<div class="col-md-6">
    <form class="submission-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ wizard.management_form }} {% if wizard.form.forms %} {{ wizard.form.management_form }} {% for form in wizard.form.forms %} {% bootstrap_form form %} {% endfor %} {% else %}
            <p><strong>{% bootstrap_form wizard.form %}</strong></p> 
            
            {% endif %}
        </table>
        {% if wizard.steps.prev %}
        <button class="btn btn-primary" name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">
          {% trans "first step" %}
        </button>
        <button class="btn btn-primary" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">
          {% trans "previous step" %}
        </button> 
        {% endif %}
        {% if wizard.steps.index < 1 %}
        <input class="btn btn-primary" type="submit" value="{% trans 'next' %}" />
        {% elif wizard.steps.index == 1 %}
        <input class="btn btn-primary" type="submit" value="{% trans 'next' %}" />
        {% elif wizard.steps.index == 2 %}
        <input class="btn btn-primary" type="submit" value="{% trans 'submit' %}" />
        {% endif %}
    </form>
</div>
{% endblock %}

templates/audits/update_site.html
{% extends "base.html" %} 

{% block content %}
<form action="" method="POST">
    {% csrf_token %} {{ form.as_p }}

    <a class="btn btn-outline-info btn-sm" href="{% url 'audits:site' %}">Return Back</a>
    <input type="submit" value="Save">
</form>

{% endblock %}

templates/audits/update_vendor.html
{% extends "base.html" %} 

{% block content %}
<form action="" method="POST">
    {% csrf_token %} 
    {{ form.as_p }}

    <a class="btn btn-outline-info btn-sm" href="{% url 'audits:all-vendor' %}">Return Back</a>
    <input type="submit" value="Save">
</form>

{% endblock %}

templates/audits/vendor_form.html
{% extends 'base.html' %} 

{% block content %}
<div class="content-section">
  <form action="" method="POST">
    {% csrf_token %}
    <fieldset class="form-group" class="uniForm">
      <legend class="border-bottom mb-4">New Vendor</legend>
      {{ form.as_p }}
    </fieldset>
    <div class="form-group">
      <a class="btn btn-outline-info btn-sm" href="{% url 'audits:all-vendor' %}">Return Back</a>
      <button class="btn btn-outline-info btn-sm" type="submit">Create</button>
    </div>
  </form>
</div>

{% endblock %}