audits/urls.py
from django.urls import path
from .views import SiteListView, ClientListView, ChecklistWizardView, VendorCreate, VendorUpdate, ChecklistTwoWizardView, ChecklistThreeWizardView
from .forms import *

from . import views

app_name = 'audits'

urlpatterns = [
    path('', views.index, name='index'),
    path('client/', ClientListView.as_view(), name='client'),
    path('client/<int:pk>/', views.clientDetail, name='client-detail'),
    path('allvendor/', views.AllVendorListView.as_view(), name='all-vendor'),
    path('site/', SiteListView.as_view(), name='site'),
    #path('vendor/', views.vendorList, name='vendor'),
    path('vendor/<int:pk>/', views.vendorDetail, name='vendor-detail'),
    path('create-site', views.createSite, name='create-site'),
    path('create-client/', views.createClient, name='create-client'),
    path('create-vendor/', VendorCreate.as_view(), name='create-vendor'),
    path('update-client/<int:pk>/', views.updateClient, name='update-client'),
    path('delete-client/<int:pk>/', views.deleteClient, name='delete-client'),
    path('update-site/<int:pk>/', views.updateSite, name='update-site'),
    path('delete-site/<int:pk>/', views.deleteSite, name='delete-site'),
    path('update-vendor/<int:pk>/', VendorUpdate.as_view(), name='update-vendor'),
    path('delete-vendor/<int:pk>/', views.deleteVendor, name='delete-vendor'),
    path('site-schedule/', views.createSchedule, name='create-schedule'),
    path('checklist-banks/', ChecklistWizardView.as_view(), name='checklist-banks'),
    path('checklist_fuel&gas-stations/', ChecklistTwoWizardView.as_view(), name='checklist-fuel&gas-stations'),
    path('checklist_c&i/', ChecklistThreeWizardView.as_view(), name='checklist-c&i'),
    path('summary/', views.summary, name='summary'),
  
]

audits_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('audits/', include('audits.urls', namespace='audits')),
    path('', include('users.urls')),
]

admin.site.index_title = "Site Audits Management"
admin.site.site_header = "Audits Management Admin"
admin.site.site_title ="Audits"


if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
   
]

templates/base.html
{% load static %} 
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,200&display=swap" rel="stylesheet" /> {% bootstrap_css %}

  <link rel="stylesheet" type="" href="{% static 'css/styles.css' %}" />
  

    
  <title>Starsight | {% block title %}{% endblock %}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    
</head>

<body>
    <!--Navbar-->
    
    <div class="grid-container">
      <header>
        {% include 'partials/_navbar.html' %}
      </header>
      <main id="main_container">

        <ul class="u-nav-links">
          {% if request.user.is_authenticated and request.user.is_staff %}
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'audits:index' %}">Manage</a></li>
          <li><a href="{% url 'audits:client' %}">All Clients</a></li>
          <li><a href="{% url 'audits:site' %}">All Sites</a></li>
          <li><a href="{% url 'audits:all-vendor' %}">All Vendors</a></li>
          {% elif request.user.is_authenticated %}
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'audits:all-vendor' %}">Vendor Account</a></li>

          {% endif %}
        </ul>
        {% block content %} 
    
        {% endblock %} 
      </main>
      {% include 'audits/footer.html' %}
    </div>
    


    
    
    


    <script type="text/javascript" src="{% static 'js/vendor.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>